#!/bin/bash
# VNC Server Setup Instructions

# This script provides instructions for setting up VNC on your homeserver
# Due to limitations in the sandbox environment, we provide these instructions
# for manual setup on your actual server

echo "=== VNC Server Setup Instructions ==="
echo ""
echo "To set up VNC on your homeserver, follow these steps:"
echo ""
echo "1. Install TigerVNC server:"
echo "   sudo apt-get update"
echo "   sudo apt-get install -y tigervnc-standalone-server tigervnc-common"
echo ""
echo "2. Create VNC configuration directory:"
echo "   mkdir -p ~/.vnc"
echo ""
echo "3. Set VNC password (will be prompted to enter password):"
echo "   vncpasswd"
echo "   # Use 'changeme' as the initial password, then change it later"
echo ""
echo "4. Create VNC startup file:"
echo "   cat > ~/.vnc/xstartup << 'EOF'"
echo "#!/bin/sh"
echo "unset SESSION_MANAGER"
echo "unset DBUS_SESSION_BUS_ADDRESS"
echo "xrdb \$HOME/.Xresources"
echo "xsetroot -solid grey"
echo "x-terminal-emulator -geometry 80x24+10+10 -ls -title \"\$VNCDESKTOP Desktop\" &"
echo "x-window-manager &"
echo "EOF"
echo ""
echo "5. Make the startup file executable:"
echo "   chmod +x ~/.vnc/xstartup"
echo ""
echo "6. Start the VNC server:"
echo "   vncserver :1 -geometry 1280x800 -depth 24"
echo ""
echo "7. Connect to the VNC server using a VNC client:"
echo "   - Address: your-server-ip:5901"
echo "   - Password: your VNC password"
echo ""
echo "8. To stop the VNC server:"
echo "   vncserver -kill :1"
echo ""
echo "Note: For a better desktop experience, you may want to install a lightweight desktop environment:"
echo "   sudo apt-get install -y xfce4 xfce4-goodies"
echo ""
echo "=== End of VNC Server Setup Instructions ==="
